# Generated by Django 4.2.23 on 2025-07-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='group',
            field=models.CharField(choices=[('performance', '成绩表现'), ('school_info', '学校信息'), ('personality', '性格特点'), ('source', '来源渠道'), ('other', '其他')], default='other', max_length=20, verbose_name='标签组别'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='标签名称'),
        ),
    ]
