# Generated by Django 5.1.11 on 2025-07-19 12:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_teacher_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='created_by',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='campus',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='campus',
            name='updated_by',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='最后修改人'),
        ),
        migrations.AddField(
            model_name='campus',
            name='updated_time',
            field=models.DateTimeField(null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='created_by',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='updated_by',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='最后修改人'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='updated_time',
            field=models.DateTimeField(null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='grade',
            name='created_by',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='grade',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='grade',
            name='updated_by',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='最后修改人'),
        ),
        migrations.AddField(
            model_name='grade',
            name='updated_time',
            field=models.DateTimeField(null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='created_by',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='updated_by',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='最后修改人'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='updated_time',
            field=models.DateTimeField(null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='student',
            name='created_by',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='student',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_by',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='最后修改人'),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_time',
            field=models.DateTimeField(null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='subject',
            name='created_by',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='subject',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='subject',
            name='updated_by',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='最后修改人'),
        ),
        migrations.AddField(
            model_name='subject',
            name='updated_time',
            field=models.DateTimeField(null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_by',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='tag',
            name='updated_by',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='最后修改人'),
        ),
        migrations.AddField(
            model_name='tag',
            name='updated_time',
            field=models.DateTimeField(null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='created_by',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='updated_by',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='最后修改人'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='updated_time',
            field=models.DateTimeField(null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='teachingclass',
            name='created_by',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='teachingclass',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='teachingclass',
            name='updated_by',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='最后修改人'),
        ),
        migrations.AddField(
            model_name='teachingclass',
            name='updated_time',
            field=models.DateTimeField(null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='created_by',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='updated_by',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='最后修改人'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='updated_time',
            field=models.DateTimeField(null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='校区地址'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='校区名称'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.campus', verbose_name='所属校区'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='容纳人数'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否可用'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=100, verbose_name='教室名称/编号'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='年级名称'),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.classroom', verbose_name='使用教室'),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='end_time',
            field=models.DateTimeField(verbose_name='课程结束时间'),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='start_time',
            field=models.DateTimeField(verbose_name='课程开始时间'),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='status',
            field=models.CharField(choices=[('scheduled', '已安排'), ('completed', '已完成'), ('cancelled', '已取消')], default='scheduled', max_length=20, verbose_name='课程状态'),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='teaching_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teachingclass', verbose_name='所属教学班'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否在读'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, verbose_name='学生姓名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_contact_info',
            field=models.CharField(blank=True, max_length=100, verbose_name='家长联系方式'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.tag', verbose_name='学生标签'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='科目名称'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='contact_info',
            field=models.CharField(blank=True, max_length=100, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='grades',
            field=models.ManyToManyField(blank=True, to='api.grade', verbose_name='可教年级'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否在职'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='api.subject', verbose_name='可教科目'),
        ),
        migrations.AlterField(
            model_name='teachingclass',
            name='class_type',
            field=models.CharField(choices=[('small_group', '小班'), ('one_on_one', '一对一')], max_length=20, verbose_name='班级类型'),
        ),
        migrations.AlterField(
            model_name='teachingclass',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.grade', verbose_name='所属年级'),
        ),
        migrations.AlterField(
            model_name='teachingclass',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='班级是否有效'),
        ),
        migrations.AlterField(
            model_name='teachingclass',
            name='name',
            field=models.CharField(max_length=100, verbose_name='班级名称'),
        ),
        migrations.AlterField(
            model_name='teachingclass',
            name='students',
            field=models.ManyToManyField(blank=True, to='api.student', verbose_name='班内学生'),
        ),
        migrations.AlterField(
            model_name='teachingclass',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.subject', verbose_name='所授科目'),
        ),
        migrations.AlterField(
            model_name='teachingclass',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.teacher', verbose_name='授课教师'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='template_name',
            field=models.CharField(max_length=100, verbose_name='模板名称'),
        ),
    ]
