# Generated by Django 4.2.23 on 2025-07-20 04:10

from django.db import migrations

def migrate_data_to_dictionary(apps, schema_editor):
    """
    Migrates data from Subject, Grade, and Tag models to the new DataDictionary model.
    """
    Subject = apps.get_model('api', 'Subject')
    Grade = apps.get_model('api', 'Grade')
    Tag = apps.get_model('api', 'Tag')
    DataDictionary = apps.get_model('api', 'DataDictionary')

    # Migrate Subjects
    for subject in Subject.objects.all():
        DataDictionary.objects.create(
            group_code='subjects',
            item_value=subject.name,
            created_by='migration',
            updated_by='migration'
        )

    # Migrate Grades
    for grade in Grade.objects.all():
        DataDictionary.objects.create(
            group_code='grades',
            item_value=grade.name,
            created_by='migration',
            updated_by='migration'
        )

    # Migrate Tags
    for tag in Tag.objects.all():
        DataDictionary.objects.create(
            group_code='tags',
            item_value=tag.name,
            created_by='migration',
            updated_by='migration'
        )

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_create_data_dictionary'),
    ]

    operations = [
        migrations.RunPython(migrate_data_to_dictionary),
    ]