# Generated by Django 4.2.23 on 2025-07-20 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_migrate_to_datadict'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created_by', models.CharField(blank=True, max_length=150, null=True, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, max_length=150, null=True, verbose_name='最后修改人')),
                ('name', models.CharField(max_length=255, verbose_name='产品名称')),
                ('subject', models.CharField(max_length=100, verbose_name='科目')),
                ('grade', models.CharField(max_length=100, verbose_name='年级')),
                ('course_type', models.CharField(max_length=100, verbose_name='课程类型')),
                ('duration_minutes', models.IntegerField(verbose_name='标准单节课时长(分钟)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created_by', models.CharField(blank=True, max_length=150, null=True, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, max_length=150, null=True, verbose_name='最后修改人')),
                ('total_lessons', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总购买课时')),
                ('used_lessons', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='已消耗课时')),
                ('enrollment_name', models.CharField(max_length=255, verbose_name='报名名称')),
                ('course_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.courseproduct', verbose_name='课程产品')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.student', verbose_name='学生')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created_by', models.CharField(blank=True, max_length=150, null=True, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, max_length=150, null=True, verbose_name='最后修改人')),
                ('name', models.CharField(max_length=255, verbose_name='学习小组名称')),
                ('enrollments', models.ManyToManyField(to='api.enrollment', verbose_name='报名记录')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created_by', models.CharField(blank=True, max_length=150, null=True, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, max_length=150, null=True, verbose_name='最后修改人')),
                ('status', models.CharField(choices=[('present', '出勤'), ('absent', '缺勤'), ('leave', '请假')], default='present', max_length=20, verbose_name='考勤状态')),
                ('schedule_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scheduleentry', verbose_name='课表条目')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '考勤记录',
                'verbose_name_plural': '考勤记录',
                'unique_together': {('schedule_entry', 'student')},
            },
        ),
    ]
