# Generated by Django 4.2.23 on 2025-07-20 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_create_core_biz_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachingclass',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='teachingclass',
            name='students',
        ),
        migrations.RemoveField(
            model_name='teachingclass',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='teachingclass',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
        migrations.RemoveField(
            model_name='scheduleentry',
            name='teaching_class',
        ),
        migrations.DeleteModel(
            name='TeachingClass',
        ),
    ]
