# Generated by Django 4.2.23 on 2025-07-20 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_old_models_and_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='classroom_name',
            field=models.CharField(default='', max_length=100, verbose_name='教室名称'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='course_name',
            field=models.CharField(default='', max_length=255, verbose_name='课程名称'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='enrollments',
            field=models.ManyToManyField(blank=True, to='api.enrollment', verbose_name='关联报名'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='grade_name',
            field=models.CharField(default='', max_length=100, verbose_name='年级名称'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='lessons_consumed',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='本节课消耗课时数'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='students',
            field=models.ManyToManyField(blank=True, to='api.student', verbose_name='参与学生'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='subject_name',
            field=models.CharField(default='', max_length=100, verbose_name='科目名称'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='teacher_name',
            field=models.CharField(default='', max_length=150, verbose_name='教师姓名'),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.classroom', verbose_name='使用教室'),
        ),
    ]
