# Generated by Django 4.2.23 on 2025-07-20 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_refactor_schedule_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='grades',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
