# Generated by Django 4.2.23 on 2025-07-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_legacy_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadictionary',
            name='subgroup',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='子分组'),
        ),
        migrations.AddField(
            model_name='student',
            name='tags',
            field=models.ManyToManyField(blank=True, limit_choices_to={'group_code': 'student_tags'}, to='api.datadictionary', verbose_name='学生标签'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='grades',
            field=models.ManyToManyField(blank=True, limit_choices_to={'group_code': 'grades'}, related_name='teachers_by_grade', to='api.datadictionary', verbose_name='可教年级'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, limit_choices_to={'group_code': 'subjects'}, related_name='teachers_by_subject', to='api.datadictionary', verbose_name='可教科目'),
        ),
    ]
