# Generated by Django 4.2.23 on 2025-07-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_update_models_v2_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadictionary',
            name='group_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='分组中文名'),
        ),
    ]
