# Generated by Django 4.2.23 on 2025-07-20 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_group_name_to_datadict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datadictionary',
            name='group_name',
        ),
    ]
