# Generated by Django 4.2.23 on 2025-07-20 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_group_name_from_datadict'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(blank=True, limit_choices_to={'group_code': 'grades'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_by_grade', to='api.datadictionary', verbose_name='年级'),
        ),
        migrations.AddField(
            model_name='student',
            name='notes',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(blank=True, max_length=100, verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tags',
            field=models.ManyToManyField(blank=True, limit_choices_to={'group_code': 'student_tags'}, related_name='students_by_tag', to='api.datadictionary', verbose_name='学生标签'),
        ),
    ]
