# Generated by Django 4.2.23 on 2025-07-20 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_fields_to_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleentry',
            name='teacher_name',
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.teacher', verbose_name='授课教师'),
        ),
    ]
