# Generated by Django 4.2.23 on 2025-07-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_change_teacher_name_to_fk_on_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleentry',
            name='teacher',
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='teacher_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='教师ID快照'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='teacher_name',
            field=models.CharField(default='', max_length=150, verbose_name='教师姓名'),
        ),
    ]
