# Generated by Django 4.2.23 on 2025-07-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_revert_teacher_fk_and_add_id_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='notes',
            field=models.TextField(blank=True, verbose_name='课程备注'),
        ),
    ]
