# Generated by Django 4.2.23 on 2025-07-20 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_add_notes_to_schedule_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseproduct',
            name='name',
        ),
    ]
