# Generated by Django 4.2.23 on 2025-07-20 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_add_course_offering_and_adjust_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='enrollment_name',
        ),
    ]
