# Generated by Django 4.2.23 on 2025-07-20 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_enrollment_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudyGroup',
        ),
    ]
