# Generated by Django 4.2.23 on 2025-07-20 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0021_remove_study_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='is_active',
        ),
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='教师姓名'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='grades',
            field=models.ManyToManyField(limit_choices_to={'group_code': 'grades'}, related_name='teachers_by_grade', to='api.datadictionary', verbose_name='可教年级'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(limit_choices_to={'group_code': 'subjects'}, related_name='teachers_by_subject', to='api.datadictionary', verbose_name='可教科目'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
    ]
