# Generated by Django 4.2.14 on 2025-07-20 15:18

from django.db import migrations

def populate_teacher_name(apps, schema_editor):
    Teacher = apps.get_model('api', 'Teacher')
    for teacher in Teacher.objects.select_related('user').all():
        if teacher.user:
            teacher.name = teacher.user.username
            teacher.save(update_fields=['name'])

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_add_nullable_teacher_name'),
    ]

    operations = [
        migrations.RunPython(populate_teacher_name),
    ]