# Generated by Django 4.2.23 on 2025-07-21 15:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0024_alter_teacher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='contact_info',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='请输入有效的手机号码。', regex='^1[3-9]\d{9}'
)], verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_contact_info',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='请输入有效的手机号码。', regex='^1[3-9]\d{9}'
)], verbose_name='家长联系方式'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
    ]
